# Generated by Django 5.0.6 on 2024-05-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_delete_myuser_alter_event_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='zip_code',
        ),
    ]
